# ==================== GitLab CI/CD 配置示例 ====================
# 微信小程序构建和上传流水线
#
# 使用说明：
#   1. 将此文件复制到项目根目录为 .gitlab-ci.yml
#   2. 在 GitLab CI/CD Settings 中配置环境变量
#   3. 推送代码或打 Tag 触发流水线

stages:
  - build
  - upload

variables:
  # Docker Registry（公网版使用 Docker Hub，内网版使用 Artifactory）
  DOCKER_REGISTRY: "artifacts.iflytek.com/cbg-docker-private/xfyun_webdev"
  ARTIFACTORY_URL: "https://artifacts.iflytek.com"

  # 镜像名称
  BUILD_IMAGE: "${DOCKER_REGISTRY}/miniprogram-builder:latest"
  UPLOAD_IMAGE: "${DOCKER_REGISTRY}/miniprogram-uploader:latest"

# ==================== 构建阶段 ====================
build:
  stage: build
  tags:
    - build-server
  image: docker:24-dind
  services:
    - docker:24-dind

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $DOCKER_REGISTRY

  script:
    # 1. 构建镜像
    - |
      docker build -f private/Dockerfile.build \
        --build-arg BUILD_VERSION="${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}" \
        --build-arg BUILD_DESCRIPTION="$CI_COMMIT_MESSAGE" \
        --build-arg GIT_BRANCH="$CI_COMMIT_REF_NAME" \
        --build-arg GIT_COMMIT="$CI_COMMIT_SHA" \
        --build-arg BUILD_MODE="${BUILD_MODE:-production}" \
        -t miniprogram-builder:temp .

    # 2. 导出制品
    - mkdir -p output
    - docker run --rm -v $(pwd)/output:/output miniprogram-builder:temp

    # 3. 上传到 Artifactory
    - |
      ARTIFACT_PATH="miniprogram/builds/${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}/build-artifact.tar.gz"
      curl -u "${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD}" \
        -T output/build-artifact.tar.gz \
        "${ARTIFACTORY_URL}/${ARTIFACT_PATH}"

    # 4. 保存制品信息
    - echo "${ARTIFACTORY_URL}/${ARTIFACT_PATH}" > artifact-url.txt

  artifacts:
    paths:
      - artifact-url.txt
    expire_in: 1 hour

  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"

# ==================== 上传阶段（生产环境）====================
upload:production:
  stage: upload
  tags:
    - upload-server
  image: docker:24-dind
  services:
    - docker:24-dind
  dependencies:
    - build

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $DOCKER_REGISTRY
    - docker pull ${UPLOAD_IMAGE} || true

  script:
    - ARTIFACT_URL=$(cat artifact-url.txt)
    - echo "制品地址：${ARTIFACT_URL}"
    - |
      docker run --rm \
        -v $(pwd)/logs:/app/logs \
        -v $(pwd)/output:/app/output \
        -e ARTIFACT_URL="${ARTIFACT_URL}" \
        -e ARTIFACT_USER="${ARTIFACTORY_USER}" \
        -e ARTIFACT_PASSWORD="${ARTIFACTORY_PASSWORD}" \
        -e MP_PRIVATE_KEY_URL="${MP_PRIVATE_KEY_URL}" \
        -e ACTION="upload" \
        -e BUILD_MODE="production" \
        -e ROBOT="${ROBOT_NUMBER:-1}" \
        -e UPLOAD_OSS="true" \
        -e API_COOKIE="${API_COOKIE}" \
        ${UPLOAD_IMAGE}

  artifacts:
    paths:
      - logs/
      - output/
    expire_in: 7 days

  rules:
    - if: $CI_COMMIT_TAG
      when: manual

  environment:
    name: production

# ==================== 上传阶段（测试/预发布环境）====================
upload:staging:
  stage: upload
  tags:
    - upload-server
  image: docker:24-dind
  services:
    - docker:24-dind
  dependencies:
    - build

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $DOCKER_REGISTRY
    - docker pull ${UPLOAD_IMAGE} || true

  script:
    - ARTIFACT_URL=$(cat artifact-url.txt)
    - echo "制品地址：${ARTIFACT_URL}"
    - |
      docker run --rm \
        -v $(pwd)/logs:/app/logs \
        -v $(pwd)/output:/app/output \
        -e ARTIFACT_URL="${ARTIFACT_URL}" \
        -e ARTIFACT_USER="${ARTIFACTORY_USER}" \
        -e ARTIFACT_PASSWORD="${ARTIFACTORY_PASSWORD}" \
        -e MP_PRIVATE_KEY_URL="${MP_PRIVATE_KEY_URL}" \
        -e ACTION="upload" \
        -e BUILD_MODE="pre" \
        -e ROBOT="${ROBOT_NUMBER:-2}" \
        -e UPLOAD_OSS="true" \
        -e API_COOKIE="${API_COOKIE}" \
        ${UPLOAD_IMAGE}

  artifacts:
    paths:
      - logs/
      - output/
    expire_in: 7 days

  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: manual
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

  environment:
    name: staging

# ==================== 预览阶段（生成二维码）====================
preview:
  stage: upload
  tags:
    - upload-server
  image: docker:24-dind
  services:
    - docker:24-dind
  dependencies:
    - build

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $DOCKER_REGISTRY
    - docker pull ${UPLOAD_IMAGE} || true

  script:
    - ARTIFACT_URL=$(cat artifact-url.txt)
    - echo "制品地址：${ARTIFACT_URL}"
    - |
      docker run --rm \
        -v $(pwd)/logs:/app/logs \
        -v $(pwd)/output:/app/output \
        -e ARTIFACT_URL="${ARTIFACT_URL}" \
        -e ARTIFACT_USER="${ARTIFACTORY_USER}" \
        -e ARTIFACT_PASSWORD="${ARTIFACTORY_PASSWORD}" \
        -e MP_PRIVATE_KEY_URL="${MP_PRIVATE_KEY_URL}" \
        -e ACTION="preview" \
        -e BUILD_MODE="${BUILD_MODE:-pre}" \
        -e UPLOAD_OSS="true" \
        -e API_COOKIE="${API_COOKIE}" \
        -e QRCODE_PATH="/app/output/preview-qrcode.png" \
        ${UPLOAD_IMAGE}

    # 显示二维码 CDN 地址
    - |
      if [ -f "output/preview-qrcode-url.txt" ]; then
        echo "=========================================="
        echo "预览二维码 CDN 地址："
        cat output/preview-qrcode-url.txt
        echo "=========================================="
      fi

  artifacts:
    paths:
      - logs/
      - output/
    expire_in: 7 days

  rules:
    - if: $CI_COMMIT_BRANCH
      when: manual

  environment:
    name: preview
